### ISSUE TITLE
client should be able to call connection's CloseAsync() multiple times.

### ISSUE THREAD

**Issue by edwin-jsi** [thebracket/LanceDbCSharp#15]
using (var cnn = new Connection(new Uri("file:///tmp/test_lance")))
{
....

    await cnn.CloseAsync();
    var open = cnn.IsOpen ? "open" : "closed";
    System.Console.WriteLine($"connection is: {open}");
}
System.Console.WriteLine("Complete");

Database Dropped (Asynchronously)
2024-12-19T05:43:41.234894706Z connection is: open
2024-12-19T05:43:41.255669727Z Unhandled exception. System.Exception: Failed to disconnect: Connection not found
2024-12-19T05:43:41.255706546Z    at LanceDbClient.Connection.Dispose(Boolean disposing) in /usr/src/hello_ffi/LanceDbClient/Connection.cs:line 244
2024-12-19T05:43:41.255713084Z    at LanceDbClient.Connection.Dispose() in /usr/src/hello_ffi/LanceDbClient/Connection.cs:line 222
2024-12-19T05:43:41.255717130Z    at Program.<Main>$(String[] args) in /usr/src/hello_ffi/ApiTestbed/Program.cs:line 226
2024-12-19T05:43:41.255721250Z    at Program.<Main>(String[] args)

**Comment by edwin-jsi** [comment]
we should allow calling dispose/close multiple times.

https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=net-9.0&redirectedfrom=MSDN#System_IDisposable_Dispose

**Comment by edwin-jsi** [comment]
verified
